<?php

/**
 * Basecatgenerica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $genericas
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getGenericas() Returns the current record's "genericas" collection
 * @method catgenerica         setId()        Sets the current record's "id" value
 * @method catgenerica         setNombre()    Sets the current record's "nombre" value
 * @method catgenerica         setGenericas() Sets the current record's "genericas" collection
 * 
 * @package    AUV
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecatgenerica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catgenerica');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('generica as genericas', array(
             'local' => 'id',
             'foreign' => 'catgenerica_id'));
    }
}