<?php

/**
 * Basecomentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $contenido
 * @property integer $usuario_id
 * @property integer $review_id
 * @property usuario $usuario
 * @property review $review
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getContenido()  Returns the current record's "contenido" value
 * @method integer    getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer    getReviewId()   Returns the current record's "review_id" value
 * @method usuario    getUsuario()    Returns the current record's "usuario" value
 * @method review     getReview()     Returns the current record's "review" value
 * @method comentario setId()         Sets the current record's "id" value
 * @method comentario setContenido()  Sets the current record's "contenido" value
 * @method comentario setUsuarioId()  Sets the current record's "usuario_id" value
 * @method comentario setReviewId()   Sets the current record's "review_id" value
 * @method comentario setUsuario()    Sets the current record's "usuario" value
 * @method comentario setReview()     Sets the current record's "review" value
 * 
 * @package    AUV
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contenido', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('review_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_comentario_usuario1', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->index('fk_comentario_review1', array(
             'fields' => 
             array(
              0 => 'review_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasOne('review', array(
             'local' => 'review_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}