<?php

/**
 * Baseusuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $foto
 * @property date $fechanacimiento
 * @property enum $sexo
 * @property string $pais
 * @property string $ciudad
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $reviews
 * @property Doctrine_Collection $sitioes
 * @property Doctrine_Collection $comentarioes
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getFoto()            Returns the current record's "foto" value
 * @method date                getFechanacimiento() Returns the current record's "fechanacimiento" value
 * @method enum                getSexo()            Returns the current record's "sexo" value
 * @method string              getPais()            Returns the current record's "pais" value
 * @method string              getCiudad()          Returns the current record's "ciudad" value
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getReviews()         Returns the current record's "reviews" collection
 * @method Doctrine_Collection getSitioes()         Returns the current record's "sitioes" collection
 * @method Doctrine_Collection getComentarioes()    Returns the current record's "comentarioes" collection
 * @method usuario             setId()              Sets the current record's "id" value
 * @method usuario             setFoto()            Sets the current record's "foto" value
 * @method usuario             setFechanacimiento() Sets the current record's "fechanacimiento" value
 * @method usuario             setSexo()            Sets the current record's "sexo" value
 * @method usuario             setPais()            Sets the current record's "pais" value
 * @method usuario             setCiudad()          Sets the current record's "ciudad" value
 * @method usuario             setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method usuario             setReviews()         Sets the current record's "reviews" collection
 * @method usuario             setSitioes()         Sets the current record's "sitioes" collection
 * @method usuario             setComentarioes()    Sets the current record's "comentarioes" collection
 * 
 * @package    AUV
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseusuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fechanacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('sexo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'M',
              1 => 'F',
             ),
             ));
        $this->hasColumn('pais', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ciudad', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('review as reviews', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('sitio as sitioes', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('comentario as comentarioes', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));
    }
}