<?php

/**
 * Basereview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $util
 * @property integer $gracioso
 * @property string $negativo
 * @property string $texto
 * @property enum $calificacion
 * @property integer $sitio_id
 * @property integer $usuario_id
 * @property sitio $sitio
 * @property usuario $usuario
 * @property Doctrine_Collection $comentarioes
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getUtil()         Returns the current record's "util" value
 * @method integer             getGracioso()     Returns the current record's "gracioso" value
 * @method string              getNegativo()     Returns the current record's "negativo" value
 * @method string              getTexto()        Returns the current record's "texto" value
 * @method enum                getCalificacion() Returns the current record's "calificacion" value
 * @method integer             getSitioId()      Returns the current record's "sitio_id" value
 * @method integer             getUsuarioId()    Returns the current record's "usuario_id" value
 * @method sitio               getSitio()        Returns the current record's "sitio" value
 * @method usuario             getUsuario()      Returns the current record's "usuario" value
 * @method Doctrine_Collection getComentarioes() Returns the current record's "comentarioes" collection
 * @method review              setId()           Sets the current record's "id" value
 * @method review              setUtil()         Sets the current record's "util" value
 * @method review              setGracioso()     Sets the current record's "gracioso" value
 * @method review              setNegativo()     Sets the current record's "negativo" value
 * @method review              setTexto()        Sets the current record's "texto" value
 * @method review              setCalificacion() Sets the current record's "calificacion" value
 * @method review              setSitioId()      Sets the current record's "sitio_id" value
 * @method review              setUsuarioId()    Sets the current record's "usuario_id" value
 * @method review              setSitio()        Sets the current record's "sitio" value
 * @method review              setUsuario()      Sets the current record's "usuario" value
 * @method review              setComentarioes() Sets the current record's "comentarioes" collection
 * 
 * @package    AUV
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basereview extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('review');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('util', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('gracioso', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('negativo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 255,
             ));
        $this->hasColumn('texto', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('calificacion', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '1',
              1 => '2',
              2 => '3',
              3 => '4',
              4 => '5',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('sitio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_review_sitio1', array(
             'fields' => 
             array(
              0 => 'sitio_id',
             ),
             ));
        $this->index('fk_review_usuario1_idx', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sitio', array(
             'local' => 'sitio_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('comentario as comentarioes', array(
             'local' => 'id',
             'foreign' => 'review_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}