<?php

/**
 * Basesitio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $categoria_id
 * @property string $latitud
 * @property string $longitud
 * @property string $direccion
 * @property string $descripcion
 * @property integer $usuario_id
 * @property integer $ciudad_id
 * @property string $imagen
 * @property string $thumbnail
 * @property string $calificacion
 * @property string $telefono
 * @property string $keywords
 * @property string $website
 * @property string $horario
 * @property categoria $categoria
 * @property usuario $usuario
 * @property ciudad $ciudad
 * @property Doctrine_Collection $sitioservicio
 * @property Doctrine_Collection $reviews
 * @property Doctrine_Collection $sitio
 * @property Doctrine_Collection $galerias
 * @property Doctrine_Collection $ofertas
 * @property Doctrine_Collection $sitio_has_servicioes
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method integer             getCategoriaId()          Returns the current record's "categoria_id" value
 * @method string              getLatitud()              Returns the current record's "latitud" value
 * @method string              getLongitud()             Returns the current record's "longitud" value
 * @method string              getDireccion()            Returns the current record's "direccion" value
 * @method string              getDescripcion()          Returns the current record's "descripcion" value
 * @method integer             getUsuarioId()            Returns the current record's "usuario_id" value
 * @method integer             getCiudadId()             Returns the current record's "ciudad_id" value
 * @method string              getImagen()               Returns the current record's "imagen" value
 * @method string              getThumbnail()            Returns the current record's "thumbnail" value
 * @method string              getCalificacion()         Returns the current record's "calificacion" value
 * @method string              getTelefono()             Returns the current record's "telefono" value
 * @method string              getKeywords()             Returns the current record's "keywords" value
 * @method string              getWebsite()              Returns the current record's "website" value
 * @method string              getHorario()              Returns the current record's "horario" value
 * @method categoria           getCategoria()            Returns the current record's "categoria" value
 * @method usuario             getUsuario()              Returns the current record's "usuario" value
 * @method ciudad              getCiudad()               Returns the current record's "ciudad" value
 * @method Doctrine_Collection getSitioservicio()        Returns the current record's "sitioservicio" collection
 * @method Doctrine_Collection getReviews()              Returns the current record's "reviews" collection
 * @method Doctrine_Collection getSitio()                Returns the current record's "sitio" collection
 * @method Doctrine_Collection getGalerias()             Returns the current record's "galerias" collection
 * @method Doctrine_Collection getOfertas()              Returns the current record's "ofertas" collection
 * @method Doctrine_Collection getSitioHasServicioes()   Returns the current record's "sitio_has_servicioes" collection
 * @method sitio               setId()                   Sets the current record's "id" value
 * @method sitio               setNombre()               Sets the current record's "nombre" value
 * @method sitio               setCategoriaId()          Sets the current record's "categoria_id" value
 * @method sitio               setLatitud()              Sets the current record's "latitud" value
 * @method sitio               setLongitud()             Sets the current record's "longitud" value
 * @method sitio               setDireccion()            Sets the current record's "direccion" value
 * @method sitio               setDescripcion()          Sets the current record's "descripcion" value
 * @method sitio               setUsuarioId()            Sets the current record's "usuario_id" value
 * @method sitio               setCiudadId()             Sets the current record's "ciudad_id" value
 * @method sitio               setImagen()               Sets the current record's "imagen" value
 * @method sitio               setThumbnail()            Sets the current record's "thumbnail" value
 * @method sitio               setCalificacion()         Sets the current record's "calificacion" value
 * @method sitio               setTelefono()             Sets the current record's "telefono" value
 * @method sitio               setKeywords()             Sets the current record's "keywords" value
 * @method sitio               setWebsite()              Sets the current record's "website" value
 * @method sitio               setHorario()              Sets the current record's "horario" value
 * @method sitio               setCategoria()            Sets the current record's "categoria" value
 * @method sitio               setUsuario()              Sets the current record's "usuario" value
 * @method sitio               setCiudad()               Sets the current record's "ciudad" value
 * @method sitio               setSitioservicio()        Sets the current record's "sitioservicio" collection
 * @method sitio               setReviews()              Sets the current record's "reviews" collection
 * @method sitio               setSitio()                Sets the current record's "sitio" collection
 * @method sitio               setGalerias()             Sets the current record's "galerias" collection
 * @method sitio               setOfertas()              Sets the current record's "ofertas" collection
 * @method sitio               setSitioHasServicioes()   Sets the current record's "sitio_has_servicioes" collection
 * 
 * @package    AUV
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesitio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sitio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('latitud', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('longitud', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ciudad_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('thumbnail', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('calificacion', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => 45,
             ));
        $this->hasColumn('telefono', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('keywords', 'string', 800, array(
             'type' => 'string',
             'length' => 800,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('horario', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));


        $this->index('fk_sitio_categoria1', array(
             'fields' => 
             array(
              0 => 'categoria_id',
             ),
             ));
        $this->index('fk_sitio_usuario1', array(
             'fields' => 
             array(
              0 => 'usuario_id',
             ),
             ));
        $this->index('fk_sitio_ciudad1', array(
             'fields' => 
             array(
              0 => 'ciudad_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id'));

        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasOne('ciudad', array(
             'local' => 'ciudad_id',
             'foreign' => 'id'));

        $this->hasMany('sitio as sitioservicio', array(
             'refClass' => 'SitioServicio',
             'refClassRelationAlias' => 'servicios',
             'local' => 'sitio_id',
             'foreign' => 'servicio_id'));

        $this->hasMany('review as reviews', array(
             'local' => 'id',
             'foreign' => 'sitio_id'));

        $this->hasMany('sitio', array(
             'refClass' => 'SitioServicio',
             'local' => 'servicio_id',
             'foreign' => 'sitio_id'));

        $this->hasMany('galeria as galerias', array(
             'local' => 'id',
             'foreign' => 'sitio_id'));

        $this->hasMany('oferta as ofertas', array(
             'local' => 'id',
             'foreign' => 'sitio_id'));

        $this->hasMany('SitioServicio as sitio_has_servicioes', array(
             'local' => 'id',
             'foreign' => 'sitio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}