<?php

/**
 * categoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class categoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object categoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('categoria');
    }
}