<?php

/**
 * genericaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class genericaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object genericaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('generica');
    }
}