<?php

/**
 * horarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class horarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object horarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('horario');
    }
}