<?php

/**
 * ofertaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ofertaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ofertaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('oferta');
    }
}