<?php

/**
 * reviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class reviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object reviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('review');
    }
}