<?php

/**
 * SitioHorarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitioHorarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitioHorarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SitioHorario');
    }
}