<?php

/**
 * SitioServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitioServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SitioServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SitioServicio');
    }
}