<?php

/**
 * servicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class servicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object servicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('servicio');
    }
}