<?php

/**
 * sitioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sitioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sitioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sitio');
    }
}