<?php

/**
 * contactoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contactoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object contactoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contacto');
    }
}