<?php

/**
 * comentarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class comentarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object comentarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('comentario');
    }
}